export default 
       [
        {
            "id": "1",
            "epNumber": "Episode 1",
            "url": "ep-one.png",
            "title": "Are you a perplexed Mind person?",
            "avatar-image": "../../images/avatar.png",
            "hostName": "jane Doe",
            "date": "sep 22, 2022",
            "minute": "(46 min)",
            "tag1": "mind-behaviour",
            "tag2": "health",
        },   
        {
            "id": "2",
            "epNumber": "Episode 2",
            "url": "ep-two.png",
            "title": "Types of social Classes of people",
            "avatar-image": "../../images/avatar.png",
            "hostName": "jane Doe",
            "date": "oct 27, 2022",
            "minute": "(55 min)",
            "tag1": "social-class",
            "tag2": "wealth",
        },    
        {
            "id": "3",
            "epNumber": "Episode 3",
            "url": "ep-three.png",
            "title": "Are you a perplexed Mind person?",
            "avatar-image": "../../images/avatar.png",
            "hostName": "jane Doe",
            "date": "sep 22, 2022",
            "minute": "(46 min)",
            "tag1": "mind-behaviour",
            "tag2": "health",
        },
        {
            "id": "4",
            "epNumber": "Episode 4",
            "url": "ep-four.png",
            "title": "How to Deal with self-confidence",
            "avatar-image": "../../images/avatar.png",
            "hostName": "jane Doe",
            "date": "sep 22, 2022",
            "minute": "(48 min)",
            "tag1": "mind-behaviour",
            "tag2": "health",
        },
        {
            "id": "5",
            "epNumber": "Episode 5",
            "url": "ep-five.png",
            "title": "Are you a perplexed Mind person?",
            "avatar-image": "../../images/avatar.png",
            "hostName": "jane Doe",
            "date": "sep 22, 2022",
            "minute": "(44 min)",
            "tag1": "mind-behaviour",
            "tag2": "health",
        },
        {
            "id": "6",
            "epNumber": "Episode 6",
            "url": "ep-six.png",
            "title": "Are you a perplexed Mind person?",
            "avatar-image": "../../images/avatar.png",
            "hostName": "jane Doe",
            "date": "sep 22, 2022",
            "minute": "(53 min)",
            "tag1": "mind-behaviour",
            "tag2": "health",
        },         
        ]
    
